wakatime/macos-wakatime

- WakaTime/ConfigFile.swift
- WakaTime/WakaTime.swift
Regarding `ConfigFile`: I added only the changes that were necessary for working with the internal config and left my parser changes out. Most notably, both `getSetting()` and `setSetting()` now have a parameter `internalConfig` defaulting to `false`. I will leave some comments inline.
A general remark: I didn't add logging. Let me know if you need it and I can add it quickly. I saw it's present e.g. in the vim extension, but wasn't sure if you wanted in in the Mac app.
> Download CLI only if newer version available (#5)

- WakaTime/WakaTime.swift
- WakaTime/Watcher.swift
The file path of the currently edited file is now always treated as a URL to allow for easy correct handling of spaces. This fixes sending updates to the CLI when the file path contains a space. Fixes #45.
> Fix publishing updates to the CLI

- .github/workflows/on_push.yml
This PR fixes changelog parsing by printing the content of variable to a file and "cat" that file as an input for `prepare_changelog.sh`.
https://github.com/wakatime/macos-wakatime/actions/runs/4543097478/jobs/8007432681
> Fix changelog when content is too long

- WakaTime/WakaTime.swift
`lastFile` and `lastTime` weren't actually updating because they were properties on a `struct`.
> Prevent sending heartbeat too frequently

- WakaTime/BundleExtension.swift
- WakaTime/Settings.swift
I got issue #54  then want to check the version number but cant find it in setting, so add it:
BTW:
1. Version: #53 should be fixed to show the correct version.
2. Build: You can consider to auto update build by commit count. [REF](https://gist.github.com/alparslandev/51ad5bc0192ad4d52ffcac02d5e3b541#file-set_build_number_by_git_commits-sh)
> Add version number to settings #54 #53

- .github/workflows/on_push.yml
- WakaTime/BundleExtension.swift
- WakaTime/ConfigFile.swift
- WakaTime/WakaTime.swift
- WakaTime/Watcher.swift
Because these strings are used in the `User-Agent` header and separated by space to find the xcode version, macos-wakatime version, and wakatime-cli version... we should prevent having spaces in the version number strings.
Also changes:
* uses the bundle extension attributes for version and build instead of reading keys directly
* removes `v` prefix from version when updating `project.yml`
> Use unknown string when version null

- .github/workflows/on_push.yml
- WakaTime/WakaTime.swift
Alan said "We should be able to disable adding as login item when built in Debug profile, then change GitHub Actions to build with a Release profile?"
This adds the debug mode check and only adds the app as a login item when in release mode.
I am not sure what (or if anything) needs to be changed in the GitHub Action?
> Only add the app as login item in release mode (#34)

- WakaTime/ConfigFile.swift
- WakaTime/WakaTime.swift
We're slowly moving all config files into `~/.wakatime/` to cleanup `$HOME`.
> Use new internal cfg location

- .github/workflows/on_push.yml
Fixes the failing github action when releasing new version:
```
Create keychain profile
This process stores your credentials securely in the Keychain. You reference these credentials later using a profile name.
Validating your credentials...
Success. Credentials validated.
Credentials saved to Keychain.
To use them, specify `--keychain-profile "notarytool-profile"`
Creating temp notarization archive
Notarize app
Conducting pre-submission checks for notarization.zip and initiating connection to the Apple notary service...
Submission ID received
id: 2e388786-0fce-4db1-bec5-920c528[34](https://github.com/wakatime/macos-wakatime/actions/runs/5199084790/jobs/9376115257#step:9:35)[38](https://github.com/wakatime/macos-wakatime/actions/runs/5199084790/jobs/9376115257#step:9:39)c
Successfully …
```
> Fix signing helper bundle

- .github/workflows/on_push.yml
- README.md
To fix https://github.com/wakatime/macos-wakatime/actions/runs/5258201829/jobs/9502147379:
```
Current status: In Progress.....
Current status: Accepted......Processing complete
id: a5e96120-9e49-461d-ac77-d984aa79e079
status: Accepted
Processing: /Users/runner/work/macos-wakatime/macos-wakatime/build/Release/WakaTime.app/Contents/Frameworks/libswift_Concurrency.dylib
The staple and validate action failed! Error 73.
Error: Process completed with exit code 73.
```
> Stop notarizing concurrency framework

- .github/workflows/on_push.yml
To fix `./bin/sparkle/generate_appcast: cannot execute binary file: Exec format error`
> Run release step on macos

- WakaTime/Watcher.swift
- project.yml
Starts work towards #103, but running into a problem:
There are too many FSEvents from background apps not currently focused. We need a way to filter only FSEvents from the currently focused application.
> Watch filesystem events noop

- project.yml
To distinguish between local builds and in-the-wild old versions, we should use `local-build` as the version sent to the API instead of a valid version number.
> Use local build version number

- .github/workflows/on_push.yml
Fixes signing because `-scheme WakaTime` builds `Debug` and we want `Release`.
> Remove scheme when building

- .github/workflows/on_push.yml
- WakaTime/Helpers/SettingsManager.swift
This uses `Debug` config when building instead of `Release`. We used `Release` to prevent adding the app as a Login Item when building locally in `Debug`, so now we're checking the version and matching against `local-build` to prevent adding as a Login Item instead of relying on the build configuration.
> Use Debug config to fix build

- WakaTime/WakaTime-Info.plist
- project.yml
Let's see if this fixes gentle toast notifications when new updates are available.
> Upgrade Sparkle to v2.5.0-beta.1

- WakaTime/AppDelegate.swift
- WakaTime/Views/SettingsView.swift
- WakaTime/WakaTime-Info.plist
- project.yml
Notifications of new updates has never worked with Sparkle, and Sparkle is unnecessarily complicated. This replaces Sparkle with [AppUpdater](https://github.com/mxcl/AppUpdater).
Leaving the appcast generation in-place for now, so old versions can still update manually by selecting `Check for updates` from the WakaTime system tray menu.
> Replace Sparkle with AppUpdater

- .github/workflows/on_push.yml
- WakaTime/AppDelegate.swift
Also removes `v` prefix from version tags because AppUpdater can't parse it.
> Show alert if no updates available

- WakaTime/AppDelegate.swift
> Truncate error alert and show version in up to date alert

- WakaTime/AppDelegate.swift
Adds a separator between the A11y request menu item and others.
> Separator under a11y menu item when visible

- WakaTime/Watcher.swift
This prevents flickering of the icon state when Xcode is loading.
> Only show warning on icon when a11y permission not granted

- WakaTime/Views/SettingsView.swift
Removes `Save` and `Cancel` buttons, and just always saves api key when changed.
> Auto save settings without buttons

- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Extensions/NSRunningApplicationExtension.swift
Fixes a bug introduced in c7f7f791fa354bb762d0a0193cc747800941b1b5 where `MonitoredApp.init` always returned `nil`.
> Fix tracking electron apps

- WakaTime/Helpers/Dependencies.swift
When not authenticated, the etag conditional header `If-Modified-Since` still counts against the IP's rate limit so it does nothing. With this PR, we're only checking for updates to wakatime-cli once every 4 hours so we don't exhaust our GitHub API rate limit.
> Rate limit checking for wakatime-cli updates, to avoid GitHub API quota

- WakaTime/Helpers/AppInfo.swift
- WakaTime/WakaTime.swift
- WakaTime/Watcher.swift
So the WakaTime API can correctly parse editor name from `User-Agent` string.
> Strip whitespace from plugin name and version

- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Watcher.swift
Adding these apps for #205 and #206 to the `Monitored Apps` menu, but they don't [yet track activity](https://github.com/wakatime/macos-wakatime/issues/205#issuecomment-1961074165).
> Add Linear, Notes, Notion, WeChat Work

- WakaTime/WakaTime.swift
Just to make sure we never execute `wakatime-cli` with an empty entity (`wakatime-cli --entity ""`) to prevent [these log messages](https://github.com/wakatime/macos-wakatime/issues/208#issuecomment-1975754116).
> Make sure entity not empty string

- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/Helpers/MonitoringManager.swift
We can't actually track some apps yet, because none of the [AXObserver events](https://github.com/wakatime/macos-wakatime/blob/main/WakaTime/Watcher.swift#L117) are triggered for these apps so we don't know when they're being used or just idle.
Related to #205, #206, #194.
> Hide un-suported apps from Monitored Apps menu

- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Views/MonitoredAppsView.swift
- WakaTime/WakaTime.swift
The `NSSwitch.tag` attribute was necessary to identify the bundleId from clicks.
> Fix toggle switch in Monitored Apps setting screen

- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/Helpers/EventSourceObserver.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Views/MonitoredAppsView.swift
- WakaTime/Watcher.swift
> Implement event source monitoring with app-specific heuristics 

- WakaTime Helper/AppDelegate.swift
- WakaTime Helper/Logging.swift
- WakaTime/AppDelegate.swift
- WakaTime/ConfigFile.swift
- WakaTime/Extensions/AXObserverExtension.swift
- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/FileSavedWatcher.swift
- WakaTime/Helpers/Dependencies.swift
- WakaTime/Helpers/PropertiesManager.swift
- WakaTime/Helpers/SettingsManager.swift
- WakaTime/Utils/Logging.swift
- WakaTime/Views/SettingsView.swift
- WakaTime/WakaTime.swift
- WakaTime/Watcher.swift
- WakaTime/WindowControllers/SettingsWindowController.swift
Improvement for #219
Note: WakaTime Helper will always log to ~/.wakatime/macos-wakatime-helper.log regardless of the "Enable Logging" setting in the WakaTime app.
> Implement logging to a file

- WakaTime/Views/SettingsView.swift
> Arrange fields in settings with api key first

- WakaTime/WakaTime.swift
This fixes a bug where switching from a monitored app to an un-monitored app then back to the monitored app would trigger a heartbeat, because `lastEntity` was set to the value from the un-monitored app. Instead, we should only set `lastEntity` from monitored apps to prevent sending heartbeats too frequently.
> Prevent sending heartbeats too often

- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/Helpers/MonitoringManager.swift
I was able to identify the project on the issue screen by looking for the "Project" label in the right sidebar. This appears to be working reliably, but it will only work for english locales. In other languages, the project won't be reported as long as we don't add our own translations.
Closes #206
> Add support for Linear

- WakaTime/Views/MonitoredAppsView.swift
- WakaTime/WindowControllers/MonitoredAppsWindowController.swift
Closes #232.
After some fiddling with the stack views, I gave up and rewrote the whole view to use a proper `NSOutlineView`, which is pretty standard on macOS. This one correctly adapts to the scroller visibility, which can be tricky on macOS and is hard to work out if you do your own customer `NSScrollView` with stack views setup.
What is more, there was a bug where, on first app launch, the Monitored Apps window would display all apps as disabled, even though the default apps were enabled (race condition) via `MonitoringManager.enableByDefault`.
I had a hard time understanding the following in the old code and I **didn't overtake it** to the new code. Please let me know if we need this and what it's supposed to do:
```
@objc func switchToggled(_ sender: NSSwitch) {
let isSetApp = …
```
> Make monitored apps scrollable

- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/Extensions/StringExtension.swift
- WakaTime/Helpers/FilterManager.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Helpers/PropertiesManager.swift
- WakaTime/Views/SettingsView.swift
- WakaTime/WindowControllers/SettingsWindowController.swift
I took the liberty to redesign the Settings window a bit:
The whitelist also supports the `@@` syntax.
Closes #196
> Add browser activity filter

- WakaTime/Extensions/StringExtension.swift
- WakaTime/Helpers/Dependencies.swift
When wakatime-cli was built from source code, disable updating wakatime-cli. The desktop app will still update automatically, just not wakatime-cli.
> Prevent upgrading wakatime-cli when built from source

- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Watchers/MonitoredApp.swift
See my comment in the source.
Closes #236
> Support tracking Canva

- WakaTime/Helpers/Dependencies.swift
- WakaTime/WakaTime.swift
> Warn when conflicting browser extension detected

- WakaTime/Helpers/PropertiesManager.swift
- WakaTime/Views/SettingsView.swift
- WakaTime/WakaTime.swift
- WakaTime/Watchers/Watcher.swift
> Ability to disable a11y permission

- CONTRIBUTING.md
- README.md
- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Watchers/MonitoredApp.swift
Using the window title from Zed, we get the currently open file name and project name. With just the file name (vs file path) we can't detect language, or other file stats. I'll look into ways to get the absolute file path of the focused file and submit a future PR if there's any solution.
> Support for Zed

- project.yml
To prevent warning:
```
You can’t open the application “WakaTime.app” because this application is not supported on this Mac
```
> Support MacOS 13.5 and newer

- .github/workflows/on_push.yml
New `macos-latest` GitHub runner defaults to ARM, but we need to support Intel:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
> Fix releases for Intel CPUs

- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Views/MonitoredAppsView.swift
- WakaTime/Watchers/MonitoredApp.swift
After #296, we'll only add support for apps when a custom `category`, `entityType`, or `project` is necessary.
If the default `coding` category and other defaults are sufficient, we don't need the bundleId hard-coded to support new apps anymore.
> Add support for more apps

- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Views/MonitoredAppsView.swift
- WakaTime/WakaTime.swift
Previously, if an app was monitored but not running then it would be missing from the `Monitored Apps` menu list.
> Always show monitored app even when not running

- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Views/MonitoredAppsView.swift
- WakaTime/WakaTime.swift
Changelog:
- Always show monitored app even when not running #315
> Release v5.23.5

- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Watchers/MonitoredApp.swift
This is a simple addition of the Chrome Beta and Chrome Canary app ID's which will allow those apps to be marked as browsing time and have the same rules applied as regular Google Chrome.
> Add support for Chrome Beta and Chrome Canary

- WakaTime/Helpers/MonitoringManager.swift
Detects project from `github.com/wakatime/macos-wakatime` as `macos-wakatime` instead of `wakatime/macos-wakatime`.
> Fix parsing project from browser url

- WakaTime/Helpers/MonitoringManager.swift
When a new plugin is added to [MonitoredApp.pluginAppIds](https://github.com/wakatime/macos-wakatime/blob/1d8fd1c7cb8214c6f32343b551ed7a3ae872b304/WakaTime/Watchers/MonitoredApp.swift#L57) that was previously enabled for tracking, there's no way to disable tracking for that app now that the toggle switch becomes a link to the plugin install page.
This PR fixes that by not tracking apps listed as having plugins.
> Exclude tracking apps that now have plugins

- WakaTime/AppDelegate.swift
- WakaTime/Helpers/Dependencies.swift
- WakaTime/WakaTime.entitlements
- WakaTime/WakaTime.swift
- project.yml
The notification warning about duplicate tracking from browser extension and desktop app isn't working, this might fix it.
> Fix browser duplicate tracker notification
