wakatime/macos-wakatime

- WakaTime/Settings.swift
- WakaTime/WakaTime.swift
- add "WakaTime" to title (make clear which app it belongs to)
- enable close button
- disable resizing
- add padding between UI elements
- add keyboard shortcuts for cancel- and save button (press esc to cancel, return to save)
> Fix settings window

- WakaTime/WakaTime-Info.plist
- WakaTime/WakaTime.swift
> Added logic to handle Settings launch on start

- WakaTime/ConfigFile.swift
> Improve ini parser

- .github/workflows/on_push.yml
This PR sets `masterBranchName` to the target branch being merged to try to fix updating `project.yml` failing.
> Configure yaml-update-action

- .github/workflows/on_push.yml
Fixes broken build:
https://github.com/wakatime/macos-wakatime/actions/runs/4544294157/jobs/8010237797
> release with empty changelog

- .github/workflows/on_push.yml
Changelog:
* First production release
> Release v0.1.0

- .github/workflows/on_push.yml
> Remove v from version

- .github/workflows/on_push.yml
Fixes https://github.com/wakatime/macos-wakatime/actions/runs/4608003887/jobs/8143594142.
> Add back version dependency to release step

- .github/workflows/on_push.yml
- WakaTime/ConfigFile.swift
- WakaTime/Helpers/AppInfo.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Views/MonitoredAppsView.swift
- WakaTime/WakaTime.swift
- WakaTime/Watcher.swift
> Support tracking more apps beyond Xcode

- WakaTime/Helpers/AppInfo.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Helpers/PropertiesManager.swift
- WakaTime/Helpers/SettingsManager.swift
- WakaTime/Settings.swift
- WakaTime/Views/MonitoredAppsView.swift
- WakaTime/WakaTime.swift
> Option for disabling launch on login

- project.yml
Fixes https://github.com/wakatime/macos-wakatime/actions/runs/5204848445/jobs/9389628444#step:12:1
> Remove libswift_Concurrency after building

- .github/workflows/on_push.yml
changelog-action requires linux
> Split release step to run on ubuntu and macos

- WakaTime/Controls/WKTextField.swift
- WakaTime/Helpers/Accessibility.swift
- WakaTime/Helpers/Dependencies.swift
- WakaTime/Helpers/SettingsManager.swift
- WakaTime/WakaTime.swift
- WakaTime/Watcher.swift
Moves some code around to make `WakaTime.swift` smaller. Also adds skeleton code for #103, printing when a key is pressed.
> Refactor main into helpers

- CONTRIBUTING.md
- WakaTime/WakaTime.swift
- WakaTime/Watcher.swift
Previously, it was highly unlikely to track time spent compiling unless the build took over 2 minutes.
Adds onto #64.
> Fix sending heartbeat when isBuilding flag changes value

- WakaTime/Watcher.swift
- project.yml
From https://github.com/eonil/FSEvents/blob/a54369c44ab9caabf611d01080e64fe30608d83f/test.zsh#L6
> Fix xcodebuild

- WakaTime/Watcher.swift
> Fix crash when calling watch() while there is no active Xcode window

- .github/workflows/on_push.yml
- WakaTime/WakaTime-Info.plist
- WakaTime/Watcher.swift
- project.yml
Changelog:
- Fix crash when calling watch while there is no active Xcode window #116
- Enable automatic download and installation of updates by default #114
- Use local build version number #111
> Release v2.1.1

- WakaTime/AppDelegate.swift
Implements #112.
Depends on #87 and must be merged after that PR.
> Gentle updates

- WakaTime/Helpers/PropertiesManager.swift
- WakaTime/Views/SettingsView.swift
- WakaTime/Watcher.swift
> Added option to enable/disable automatic updates

- .github/workflows/on_push.yml
- WakaTime/Helpers/PropertiesManager.swift
- WakaTime/Views/SettingsView.swift
- WakaTime/Watcher.swift
Changelog:
- Added option to enable/disable automatic updates #128
> Release v2.3.0

- WakaTime/AppDelegate.swift
- WakaTime/Views/SettingsView.swift
- WakaTime/WakaTime-Info.plist
- project.yml
Changelog:
- Replace Sparkle with AppUpdater #134
> Release v2.4.0

- .github/workflows/on_push.yml
According to https://github.com/mxcl/AppUpdater/tree/master#caveats.
> Fix asset name for auto updates

- .github/workflows/on_push.yml
Fixes `Pattern '"./release/wakatime-v3.0.2-alpha.1.zip"' does not match any files.`
> Fix release asset uploading

- .github/workflows/on_push.yml
- WakaTime/AppDelegate.swift
- project.yml
Changelog:
- Fix auto updates #142
> Release v3.0.4

- .github/workflows/on_push.yml
- README.md
Removed version from download to always have the same url from docs.
> New asset zip filename

- WakaTime/Helpers/AppInfo.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/WakaTime.swift
- WakaTime/Watcher.swift
Using the window title as `entity` because we don't have access to a file path.
> Support tracking Figma and Postman

- WakaTime/AppDelegate.swift
- WakaTime/WakaTime.swift
> Show notification when updating from menu selection

- WakaTime/Extensions/AXUIElementExtension.swift
Use correct separator based on app.
> Split window title based on focused app

- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/WakaTime.swift
Also, language shouldn't be set for messaging apps.
> Support for Zoom and WhatsApp

- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/WakaTime.swift
> Disable new apps by default

- WakaTime/AppDelegate.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Helpers/PropertiesManager.swift
- WakaTime/WakaTime.swift
Changelog:
- Disable new apps by default #190
- Always try presenting toast notification after checking permission #188
> Release v5.0.0

- README.md
- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/Helpers/MonitoringManager.swift
> Add support for Safari Technology Preview

- README.md
- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/WakaTime.swift
Changelog:
- Add support for Safari Technology Preview #198
> Release v5.1.0

- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Views/MonitoredAppsView.swift
> Support for apps installed via Setapp

- WakaTime/Views/MonitoredAppsView.swift
> Prevent hidden apps from showing in Monitored Apps menu

- .github/ISSUE_TEMPLATE/support-app-request.yaml
- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Views/MonitoredAppsView.swift
- WakaTime/WakaTime.swift
- WakaTime/Watcher.swift
Changelog:
- Add Linear, Notes, Notion, WeChat Work #207
- Make sure entity not empty string #209
- Hide un-suported apps from Monitored Apps menu #210
- Prevent hidden apps from showing in Monitored Apps menu #212
> Release v5.5.3

- WakaTime/Helpers/MonitoringManager.swift
Fixes a bug introduced in #203.
> Fix bug that prevents monitoring all apps

- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Views/MonitoredAppsView.swift
- WakaTime/WakaTime.swift
Changelog:
- Fix bug that prevents monitoring all apps #213
- Fix linter #215
- Fix toggle switch in Monitored Apps setting screen #216
> Release v5.5.5

- WakaTime Helper/AppDelegate.swift
- WakaTime Helper/Logging.swift
- WakaTime/AppDelegate.swift
- WakaTime/ConfigFile.swift
- WakaTime/Extensions/AXObserverExtension.swift
- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/FileSavedWatcher.swift
- WakaTime/Helpers/Dependencies.swift
- WakaTime/Helpers/EventSourceObserver.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Helpers/PropertiesManager.swift
- WakaTime/Helpers/SettingsManager.swift
- WakaTime/Utils/Logging.swift
- WakaTime/Views/MonitoredAppsView.swift
- WakaTime/Views/SettingsView.swift
- WakaTime/WakaTime.swift
- WakaTime/Watcher.swift
- WakaTime/WindowControllers/SettingsWindowController.swift
Changelog:
- Implement event source monitoring with app-specific heuristics #218
- Minor debug code changes #217
- Fix entity type for non-Xcode reporting #220
- Implement logging to a file #221
> Release v5.7.0

- WakaTime/Views/SettingsView.swift
- WakaTime/WakaTime.swift
Changelog:
- Prevent sending heartbeats too often #224
> Release v5.7.1

- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/WakaTime.swift
- WakaTime/Watcher.swift
Note:
* This includes the functions that I wrote for extracting elements at index paths and by patterns. It's useful for developing mainly and not used to identify the address field. There we use the heuristic with the URL detection as discussed.
* Firefox doesn't work w.r.t. the project extraction, but the window title extraction works. It appears opaque to the AX APIs for some reason that I don't understand.
> Detect project from browser address fields

- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Extensions/NSRunningApplicationExtension.swift
- WakaTime/Helpers/EventSourceObserver.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Views/SettingsView.swift
- WakaTime/WakaTime.swift
- WakaTime/Watcher.swift
Changelog:
- Detect project from browser address fields #229
- Improve watcher performance by only starting timer for monitored apps #230
> Release v5.8.1

- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Extensions/URLExtension.swift
Changelog:
- Fix parsing URL without scheme #245
> Release v5.13.2

- README.md
- WakaTime/Helpers/Dependencies.swift
- WakaTime/Helpers/PropertiesManager.swift
- WakaTime/Views/SettingsView.swift
- WakaTime/WakaTime.swift
- WakaTime/Watchers/Watcher.swift
Changelog:
- Ability to disable a11y permission #263
- Fix supported apps source code link #257
> Release v5.15.0

- WakaTime/Watchers/MonitoredApp.swift
> Support GitHub Desktop Client

- WakaTime/AppDelegate.swift
- WakaTime/Helpers/PropertiesManager.swift
- WakaTime/Views/SettingsView.swift
- WakaTime/WakaTime.swift
- WakaTime/WindowControllers/SettingsWindowController.swift
> Show today time in status bar

- WakaTime/AppDelegate.swift
Have to use deprecated `statusBarItem.popUpMenu` because `statusBarItem.menu` disables the `onClick` action handler.
Also, fetching code time text on application start.
> Refresh code time text when status bar icon clicked

- WakaTime/AppDelegate.swift
- WakaTime/Helpers/MonitoringManager.swift
Changelog:
- Fix status bar time empty while fetching #307
> Release v5.23.2

- WakaTime/AppDelegate.swift
- WakaTime/Watchers/Watcher.swift
Only when focused app window changed, so won't refresh if computer is idle.
> Refresh status bar code time every 2 mins

- WakaTime/AppDelegate.swift
- WakaTime/Watchers/Watcher.swift
Changelog:
- Refresh status bar code time every 2 mins #311
> Release v5.23.3

- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/WakaTime.swift
By parsing page text using Apple's accessibility API looking for `Languages` text, then getting the first language A link from children.
> Detect language from GitHub repo

- WakaTime/Extensions/AXUIElementExtension.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Views/MonitoredAppsView.swift
- WakaTime/WakaTime.swift
Changelog:
- Detect language from GitHub repo #317
> Release v5.24.0

- WakaTime/Helpers/MonitoringManager.swift
> Fix getting url for Arc Browser

- .github/workflows/on_push.yml
- WakaTime/Helpers/MonitoringManager.swift
Changelog:
- Fix parsing project from browser url #330
> Release v5.26.4

- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Watchers/MonitoredApp.swift
Changelog:
- Link to Cursor plugin #332
> Release v5.27.0

- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Watchers/MonitoredApp.swift
Changelog:
- Exclude tracking apps that now have plugins #334
> Release v5.27.1

- WakaTime/AppDelegate.swift
- WakaTime/Helpers/Dependencies.swift
- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/WakaTime.entitlements
- WakaTime/WakaTime.swift
- project.yml
Changelog:
- Fix browser duplicate tracker notification #337
> Release v5.27.2

- WakaTime/Helpers/MonitoringManager.swift
- WakaTime/Watchers/MonitoredApp.swift
Adds Inkscape to the list of monitored applications. 
Configures title extraction, activity type, and display name.
> Add support for Inkscape
